# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members =["clock"]

[workspace.dependencies]
iced = "0.13.1"
chrono = "0.4"
tracing-subscriber = "0.3"
