name: Rust-wasm-deploy

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build_without-bundler:
    uses: ./.github/workflows/reusable-build.yml
    with:
      dir-name: without-bundler
  build_clock:
    uses: ./.github/workflows/reusable-build.yml
    with:
      dir-name: clock
