name: Rust-wasm-deploy

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: jetli/trunk-action@v0.5.0
        with:
          # Optional version of trunk to install(eg. 'v0.19.1', 'latest')
          version: "latest"

      - name: Build with trunk
        run: rustup target add wasm32-unknown-unknown && cd without-bundler && RUSTFLAGS='--cfg=web_sys_unstable_apis' trunk build --release --public-url /iced-examples
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./without-bundler/dist
          force_orphan: true
